apiVersion: v1
kind: Pod
metadata:
  name: mutli-container
  labels:
    purpose: mutli-container
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
    command: ["sleep", "1000"]